### ISSUE TITLE
The response is not parsed propertly (lastIndexProcessed)

### ISSUE THREAD

**Issue by yunusyuksel** [binaryminds/react-native-sse#22]
I have a server that runs on https://github.com/sysid/sse-starlette
With sse-startlette the parsing of response does not work propertly. 

The lastIndexProcessed is set to 1 since lastIndexOf('\n\n') is not found on response text

**Comment by GilbertYoder** [comment]
Found this same issue after beating my head against the wall all day. Not sure why but some messages get passed to the `_handleEvent()` method in their entirety, while others get passed in in chunks. In the latter case, `lastIndexProcessed` gets set to 1 because response does not contain `\n\n` and `line` becomes `ata: ...`. Thus the event is never dispatched.
