### ISSUE TITLE
The data is logged only after the stream ends.

### ISSUE THREAD

**Issue by CelestialAzure** [binaryminds/react-native-sse#26]
The server sent stream data is only logged on console once the entire stream ends. Not sure how to go about fixing this.

- Code Sample -
const url = new URL("....");
const es = new EventSource(url, {
  headers: {
    "Content-Type": "application/json",
    Accept: "text/event-stream",
    "X-SS-API-KEY": "",
    "X-SSUID": "",
    "X-SSPID": "",
    Authorization: `bearer ${token}`,
    Connection: "keep-alive",
  },
  method: "POST",
  body: JSON.stringify(data),
  pollingInterval: 10000,
  timeout: 10000,
});

es.addEventListener("message", e => {
  console.log("message:", JSON.parse(e.data));
});

**Comment by antondrob** [comment]
@CelestialAzure did you fix this issue? I experience the same one.

**Comment by antondrob** [comment]
The problem is with Flipper. This will fix the issue https://github.com/facebook/react-native/issues/28835#issuecomment-1644380370

**Comment by BuddhaBing** [comment]
I have the same issue on iOS

**Comment by pokaru** [comment]
I'm guessing the fix is still underway?

**Comment by EmilJunker** [comment]
> I'm guessing the fix is still underway?

The problem is not on our side. We cannot fix it. As it stands, any kind of SSE connections (regardless of which library you use) will not work in React Native debug builds on Android.

Here is what you can do:

A) Build your app in release mode. The SSE connection should work just fine then.

B) Disable Flipper by commenting out the corresponding lines of code in some Java/Kotlin file located under the android folder of your project. The exact location depends on the React Native version you're using. In never versions of React Native, I think it's somewhere in the MainActivity or MainApplication file. Once you've commented out Flipper, SSE should work also in debug builds.

C) Possibly wait for the next major release of React Native which (if I understand it correctly) will no longer include Flipper by default, so there is a chance this issue will just resolve itself: https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#flipper--react-native-integration

**Comment by pokaru** [comment]
@EmilJunker, thanks for the info.
