### ISSUE TITLE
SSE in background app 

### ISSUE THREAD

**Issue by BrianCortes** [binaryminds/react-native-sse#60]
I have a question how the SSE work when the app is background ? 

I am trying getting messages from the server when the app is in background but it doesn't work properly, anyone knows if this is possible or what other technology should a use.

**Comment by karaushu** [comment]
You can try Push Notifications they works fine in background.

**Comment by wojciechkrol** [comment]
It depends on what you want to achieve. Due to the significant limitations on background app activity on iOS, an app that operates in this way will be quickly terminated by the system. With Android, the situation is slightly better, but the app will still be put to sleep after a while and stop functioning in the background. As mentioned by @karaushu above, I recommend configuring Push Notifications and handling user action.
